config/routes.rb
TaskManageProject::Application.routes.draw do

  resources :users

  root to: "static_pages#home"

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :projects
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new()
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to @user, notice: "Welcome aboard!"
  	else
  		render 'new', alert: "Oops, try again."
  		# what is render
  		# it w
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

private
  
  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManageProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |type, msg| %>
		<div class="<%= type %>">
		  <%= msg %>
		</div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Me to You</h1>
<h3>Get Connected to Your Team!</h3>
<%= button_to "Create a free account!", new_user_path, method: :get %>
<%= button_to "Already Connected? Sign in", '#' %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Create a free account</h1>
<%= form_for @user do |f| %>
	<div class="field">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Create your free account" %>
	</div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.first_name %>!!!</h1>